/* Generated By:JavaCC: Do not edit this line. AnalizadorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int If = 11;
  /** RegularExpression Id. */
  int Else = 12;
  /** RegularExpression Id. */
  int While = 13;
  /** RegularExpression Id. */
  int Void = 14;
  /** RegularExpression Id. */
  int Main = 15;
  /** RegularExpression Id. */
  int Return = 16;
  /** RegularExpression Id. */
  int Int = 17;
  /** RegularExpression Id. */
  int Float = 18;
  /** RegularExpression Id. */
  int OPDIF = 19;
  /** RegularExpression Id. */
  int OPASIG = 20;
  /** RegularExpression Id. */
  int PUNCOMA = 21;
  /** RegularExpression Id. */
  int OPCOMA = 22;
  /** RegularExpression Id. */
  int PARIZ = 23;
  /** RegularExpression Id. */
  int PARDER = 24;
  /** RegularExpression Id. */
  int CORIZ = 25;
  /** RegularExpression Id. */
  int CORDER = 26;
  /** RegularExpression Id. */
  int SIMBNOVALIDO = 27;
  /** RegularExpression Id. */
  int IDNOVALIDO = 28;
  /** RegularExpression Id. */
  int NUMNOVALIDO = 29;
  /** RegularExpression Id. */
  int LLAVIZ = 30;
  /** RegularExpression Id. */
  int LLAVDER = 31;
  /** RegularExpression Id. */
  int ID = 32;
  /** RegularExpression Id. */
  int NUM = 33;
  /** RegularExpression Id. */
  int NUMDEC = 34;
  /** RegularExpression Id. */
  int OPSUMA = 35;
  /** RegularExpression Id. */
  int OPRESTA = 36;
  /** RegularExpression Id. */
  int OPMULTIPLICA = 37;
  /** RegularExpression Id. */
  int OPDIV = 38;
  /** RegularExpression Id. */
  int OPMENOR = 39;
  /** RegularExpression Id. */
  int OPMENORIGUAL = 40;
  /** RegularExpression Id. */
  int OPMAYOR = 41;
  /** RegularExpression Id. */
  int OPMAYORIGUAL = 42;
  /** RegularExpression Id. */
  int OPIGUALIGUAL = 43;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int DentroComentario = 1;
  /** Lexical state. */
  int DentroComentario2 = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"//\"",
    "\"\\n\"",
    "<token of kind 10>",
    "<If>",
    "<Else>",
    "<While>",
    "<Void>",
    "<Main>",
    "<Return>",
    "<Int>",
    "<Float>",
    "\"!=\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<SIMBNOVALIDO>",
    "<IDNOVALIDO>",
    "<NUMNOVALIDO>",
    "\"{\"",
    "\"}\"",
    "<ID>",
    "<NUM>",
    "<NUMDEC>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "<token of kind 44>",
  };

}
